from  services.buscaCredor import buscarCredor
import time

time.sleep(3)
#BUSCAR CREDOR POR RAZÃO SOCIAL
buscarCredor("SOFTPLAN")
#APERTAR NO BOTAO CONSULTAR

#ESPERAR 2 SEGUNDOS

#CLICAR NO LAPIS PARA EDICAO DO CREDOR

#ESPERAR 2 SEGUNDOS

#CLICAR NA ABA CONTATOS

#SCROLLA A TELA

#CLICA EM ADICIONAR

#CLICA NO INPUT NOME 

#ADICIONA NOME DO CREDOR NESSE CAMPO

#CLICA NA CHECKBOX REMOVER MASCARA 

#CLICA NO INPUT TELEFONE  

#ADICIONA TELEFONE

#CLICA NO INPUT EMAIL

#ADICIONA EMAIL

#CLICA EM SALVAR 

#CLICA EM CREDORES 