from  services.buscaCredor import buscarCredor
from  services.editarCredor import editarCredor
import time

time.sleep(3)
#BUSCAR CREDOR POR RAZÃO SOCIAL
#APERTAR NO BOTAO CONSULTAR
#ESPERAR 2 SEGUNDOS
#CLICAR NO LAPIS PARA EDICAO DO CREDOR
#ESPERAR 2 SEGUNDOS

#buscarCredor("SOFTPLAN")

#CLICAR NA ABA CONTATOS
#SCROLLA A TELA
#CLICA EM ADICIONAR
#CLICA NO INPUT NOME 
#ADICIONA NOME DO CREDOR NESSE CAMPO
#CLICA NA CHECKBOX REMOVER MASCARA 
#CLICA NO INPUT TELEFONE  
#ADICIONA TELEFONE
#CLICA NO INPUT EMAIL
#ADICIONA EMAIL
editarCredor("Contato 1", "19971436845", "joao.silva@gmail.com")



#CLICA EM SALVAR 

#CLICA EM CREDORES 